spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: root
    platform: mysql
    #启动时需要初始化的建表语句  https://blog.csdn.net/u012326462/article/details/82080812
    schema: classpath:schema/schema.sql
    #初始化的数据
    data: classpath:schema/data.sql
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
    continue-on-error: false
    sql-script-encoding: utf-8
    #sql语句 以 ；未结束符
    separator: ;

mybatis:
  mapper-locations: classpath:mapper/base/*.xml